stages:
  - test

variables:
  DEBIAN_FRONTEND: noninteractive
  GRADLE_ARGS: --no-daemon --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

.tests:
  stage: test
  script: ./gradlew ${GRADLE_ARGS} check
  artifacts:
    reports:
      junit:
        - "build/test-results/**/TEST-*.xml"

tests:jdk-8:
  extends: .tests
  image: eclipse-temurin:8
  before_script:
    - apt-get update
    - apt-get install -y git

tests:jdk-11:
  extends: tests:jdk-8
  image: eclipse-temurin:11

tests:jdk-17:
  extends: tests:jdk-8
  image: eclipse-temurin:17

tests:macos:
  extends: .tests
  tags:
    - macos

tests:windows64:
  extends: .tests
  script: gradlew.bat %GRADLE_ARGS% check
  tags:
    - windows
